on: [ push ]

name: build and test

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y
          git
          bash
          cmake
          make
          g++
          libatomic-ops-dev
          autoconf
          libgsl-dev
          zlib1g-dev
          libzstd-dev
          libjemalloc-dev
      - name: Init and update submodules
        run: git submodule update --init --recursive
      - name: Build seqwish
        run: sed -i 's/CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -O3 -mcx16 -g/CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -O -mcx16 -g -fsanitize=address/g' CMakeLists.txt && sed -i 's/CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O3 -mcx16 -g/CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O -mcx16 -g -fsanitize=address/g' CMakeLists.txt && cmake -H. -Bbuild && cmake --build build -- -j 2
      - name: Execute tests
        run: cd test && ASAN_OPTIONS=detect_leaks=1:symbolize=1 LSAN_OPTIONS=verbosity=0:log_threads=1 make test

